# Generated by Django 4.2.5 on 2023-10-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_geeksmodel_delete_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('descript', models.CharField(max_length=50)),
                ('original_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
