# Generated by Django 4.2.5 on 2023-10-27 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_geeksmodel_delete_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geeksmodel',
            old_name='name',
            new_name='descript',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='password',
            field=models.CharField(default=2009, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='user_id',
            field=models.CharField(default=datetime.date, max_length=50),
            preserve_default=False,
        ),
    ]
