# Generated by Django 4.2.5 on 2023-10-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_name_geeksmodel_descript_geeksmodel_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='user_id',
        ),
    ]
